/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : bigint,
  'ram' : [] | [string],
  'status' : AssetStatus,
  'employeeCode' : [] | [string],
  'purchaseDate' : [] | [string],
  'storage' : [] | [string],
  'name' : string,
  'createdAt' : Time,
  'invoiceNumber' : [] | [string],
  'serialNumber' : string,
  'notes' : [] | [string],
  'category' : AssetCategory,
  'warrantyDate' : [] | [string],
  'assignedUser' : [] | [string],
  'assetTag' : [] | [string],
  'processorType' : [] | [string],
  'location' : string,
  'vendorName' : [] | [string],
  'photoId' : [] | [ExternalBlob],
}
export type AssetCategory = { 'desktop' : null } |
  { 'other' : null } |
  { 'laptop' : null } |
  { 'server' : null } |
  { 'printer' : null } |
  { 'monitor' : null } |
  { 'peripheral' : null };
export interface AssetInput {
  'id' : [] | [bigint],
  'ram' : [] | [string],
  'status' : AssetStatus,
  'employeeCode' : [] | [string],
  'purchaseDate' : [] | [string],
  'storage' : [] | [string],
  'name' : string,
  'invoiceNumber' : [] | [string],
  'serialNumber' : string,
  'notes' : [] | [string],
  'category' : AssetCategory,
  'warrantyDate' : [] | [string],
  'assignedUser' : [] | [string],
  'assetTag' : [] | [string],
  'processorType' : [] | [string],
  'location' : string,
  'vendorName' : [] | [string],
  'photoId' : [] | [ExternalBlob],
}
export type AssetStatus = { 'assigned' : null } |
  { 'inStorage' : null } |
  { 'available' : null } |
  { 'inRepair' : null } |
  { 'retired' : null };
export interface AssignmentHistoryEntry {
  'id' : bigint,
  'changedBy' : Principal,
  'toStatus' : AssetStatus,
  'assetId' : bigint,
  'fromStatus' : AssetStatus,
  'toAssignee' : [] | [string],
  'timestamp' : Time,
  'assetName' : string,
  'fromAssignee' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface LocalUser {
  'id' : bigint,
  'accessLevel' : string,
  'employeeCode' : string,
  'username' : string,
  'name' : string,
  'email' : string,
  'notes' : [] | [string],
  'department' : string,
}
export interface LocalUserInput {
  'accessLevel' : string,
  'employeeCode' : string,
  'username' : string,
  'password' : string,
  'name' : string,
  'email' : string,
  'notes' : [] | [string],
  'department' : string,
}
export type Principal = Principal;
export interface Stats {
  'assigned' : bigint,
  'total' : bigint,
  'available' : bigint,
  'inRepair' : bigint,
}
export interface StoreSoftware {
  'id' : bigint,
  'assignedTo' : [] | [string],
  'purchaseDate' : [] | [string],
  'name' : string,
  'createdAt' : Time,
  'invoiceNumber' : [] | [string],
  'licenseType' : [] | [string],
  'vendor' : string,
  'notes' : [] | [string],
  'licenseKey' : [] | [string],
  'assetTag' : [] | [string],
  'licenseExpiry' : [] | [string],
}
export interface StoreSoftwareInput {
  'id' : [] | [bigint],
  'assignedTo' : [] | [string],
  'purchaseDate' : [] | [string],
  'name' : string,
  'invoiceNumber' : [] | [string],
  'licenseType' : [] | [string],
  'vendor' : string,
  'notes' : [] | [string],
  'licenseKey' : [] | [string],
  'assetTag' : [] | [string],
  'licenseExpiry' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole { 'principal' : Principal, 'role' : UserRole }
export interface WarrantyStats {
  'expiringSoon' : bigint,
  'total' : bigint,
  'active' : bigint,
  'expired' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAsset' : ActorMethod<[AssetInput], bigint>,
  'addLocalUser' : ActorMethod<[LocalUserInput], bigint>,
  'addSoftware' : ActorMethod<[StoreSoftwareInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], boolean>,
  'deleteAsset' : ActorMethod<[bigint], undefined>,
  'deleteLocalUser' : ActorMethod<[bigint], undefined>,
  'deleteSoftware' : ActorMethod<[bigint], undefined>,
  'getAllAssets' : ActorMethod<[], Array<Asset>>,
  'getAllLocalUsers' : ActorMethod<[], Array<LocalUser>>,
  'getAllSoftware' : ActorMethod<[], Array<StoreSoftware>>,
  'getAllUsersWithRoles' : ActorMethod<[], Array<UserWithRole>>,
  'getAsset' : ActorMethod<[bigint], Asset>,
  'getAssetsByCategory' : ActorMethod<[AssetCategory], Array<Asset>>,
  'getAssetsByLocation' : ActorMethod<[string], Array<Asset>>,
  'getAssetsByStatus' : ActorMethod<[AssetStatus], Array<Asset>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHistory' : ActorMethod<[], Array<AssignmentHistoryEntry>>,
  'getHistoryForAsset' : ActorMethod<[bigint], Array<AssignmentHistoryEntry>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWarrantyStats' : ActorMethod<[], WarrantyStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginLocalUser' : ActorMethod<
    [string, string],
    [] | [{ 'id' : bigint, 'accessLevel' : string, 'name' : string }]
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAssets' : ActorMethod<[string], Array<Asset>>,
  'updateAsset' : ActorMethod<[bigint, AssetInput], undefined>,
  'updateLocalUser' : ActorMethod<[bigint, LocalUserInput], undefined>,
  'updateSoftware' : ActorMethod<[bigint, StoreSoftwareInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];