/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AssetStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'inStorage' : IDL.Null,
  'available' : IDL.Null,
  'inRepair' : IDL.Null,
  'retired' : IDL.Null,
});
export const AssetCategory = IDL.Variant({
  'desktop' : IDL.Null,
  'other' : IDL.Null,
  'laptop' : IDL.Null,
  'server' : IDL.Null,
  'printer' : IDL.Null,
  'monitor' : IDL.Null,
  'peripheral' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AssetInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'ram' : IDL.Opt(IDL.Text),
  'status' : AssetStatus,
  'employeeCode' : IDL.Opt(IDL.Text),
  'windowsVersion' : IDL.Opt(IDL.Text),
  'purchaseDate' : IDL.Opt(IDL.Text),
  'storage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'invoiceNumber' : IDL.Opt(IDL.Text),
  'serialNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : AssetCategory,
  'warrantyDate' : IDL.Opt(IDL.Text),
  'assignedUser' : IDL.Opt(IDL.Text),
  'assetTag' : IDL.Opt(IDL.Text),
  'processorType' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'vendorName' : IDL.Opt(IDL.Text),
  'photoId' : IDL.Opt(ExternalBlob),
});
export const HistoryEntryInput = IDL.Record({
  'action' : IDL.Text,
  'changedBy' : IDL.Text,
  'newAssignee' : IDL.Opt(IDL.Text),
  'assetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'assetName' : IDL.Text,
  'assetType' : IDL.Text,
  'previousAssignee' : IDL.Opt(IDL.Text),
});
export const LocalUserInput = IDL.Record({
  'accessLevel' : IDL.Text,
  'employeeCode' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'department' : IDL.Text,
});
export const StoreSoftwareInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'assignedTo' : IDL.Opt(IDL.Text),
  'purchaseDate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'invoiceNumber' : IDL.Opt(IDL.Text),
  'licenseType' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'licenseKey' : IDL.Opt(IDL.Text),
  'assetTag' : IDL.Opt(IDL.Text),
  'licenseExpiry' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Time = IDL.Int;
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'ram' : IDL.Opt(IDL.Text),
  'status' : AssetStatus,
  'employeeCode' : IDL.Opt(IDL.Text),
  'windowsVersion' : IDL.Opt(IDL.Text),
  'purchaseDate' : IDL.Opt(IDL.Text),
  'storage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'invoiceNumber' : IDL.Opt(IDL.Text),
  'serialNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : AssetCategory,
  'warrantyDate' : IDL.Opt(IDL.Text),
  'assignedUser' : IDL.Opt(IDL.Text),
  'assetTag' : IDL.Opt(IDL.Text),
  'processorType' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'vendorName' : IDL.Opt(IDL.Text),
  'photoId' : IDL.Opt(ExternalBlob),
});
export const LocalUser = IDL.Record({
  'id' : IDL.Nat,
  'accessLevel' : IDL.Text,
  'employeeCode' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'department' : IDL.Text,
});
export const StoreSoftware = IDL.Record({
  'id' : IDL.Nat,
  'assignedTo' : IDL.Opt(IDL.Text),
  'purchaseDate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'invoiceNumber' : IDL.Opt(IDL.Text),
  'licenseType' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'licenseKey' : IDL.Opt(IDL.Text),
  'assetTag' : IDL.Opt(IDL.Text),
  'licenseExpiry' : IDL.Opt(IDL.Text),
});
export const UserWithRole = IDL.Record({
  'principal' : Principal,
  'role' : UserRole,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FlexHistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'changedBy' : IDL.Text,
  'newAssignee' : IDL.Opt(IDL.Text),
  'assetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'assetName' : IDL.Text,
  'assetType' : IDL.Text,
  'previousAssignee' : IDL.Opt(IDL.Text),
});
export const AssignmentHistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'changedBy' : Principal,
  'toStatus' : AssetStatus,
  'assetId' : IDL.Nat,
  'fromStatus' : AssetStatus,
  'toAssignee' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'assetName' : IDL.Text,
  'fromAssignee' : IDL.Opt(IDL.Text),
});
export const MigrationStats = IDL.Record({
  'historyCount' : IDL.Nat,
  'softwareCount' : IDL.Nat,
  'userCount' : IDL.Nat,
  'assetCount' : IDL.Nat,
});
export const Stats = IDL.Record({
  'assigned' : IDL.Nat,
  'total' : IDL.Nat,
  'available' : IDL.Nat,
  'inRepair' : IDL.Nat,
});
export const WarrantyStats = IDL.Record({
  'expiringSoon' : IDL.Nat,
  'total' : IDL.Nat,
  'active' : IDL.Nat,
  'expired' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func([AssetInput], [IDL.Nat], []),
  'addAssetWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, AssetInput],
      [IDL.Nat],
      [],
    ),
  'addHistoryEntry' : IDL.Func([HistoryEntryInput], [IDL.Nat], []),
  'addHistoryEntryWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, HistoryEntryInput],
      [IDL.Nat],
      [],
    ),
  'addLocalUser' : IDL.Func([LocalUserInput], [IDL.Nat], []),
  'addLocalUserWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, LocalUserInput],
      [IDL.Nat],
      [],
    ),
  'addSoftware' : IDL.Func([StoreSoftwareInput], [IDL.Nat], []),
  'addSoftwareWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, StoreSoftwareInput],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([Principal, UserRole], [], []),
  'batchAddAssets' : IDL.Func([IDL.Vec(AssetInput)], [IDL.Vec(IDL.Nat)], []),
  'batchAddHistory' : IDL.Func(
      [IDL.Vec(HistoryEntryInput)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'batchAddSoftware' : IDL.Func(
      [IDL.Vec(StoreSoftwareInput)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'batchAddUsers' : IDL.Func([IDL.Vec(LocalUserInput)], [IDL.Vec(IDL.Nat)], []),
  'bootstrapAdmin' : IDL.Func([], [IDL.Bool], []),
  'createFirstLocalUser' : IDL.Func(
      [LocalUserInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'deleteAsset' : IDL.Func([IDL.Nat], [], []),
  'deleteAssetWithCreds' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteLocalUser' : IDL.Func([IDL.Nat], [], []),
  'deleteLocalUserWithCreds' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteSoftware' : IDL.Func([IDL.Nat], [], []),
  'deleteSoftwareWithCreds' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getAllLocalUsers' : IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
  'getAllSoftware' : IDL.Func([], [IDL.Vec(StoreSoftware)], ['query']),
  'getAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'getAsset' : IDL.Func([IDL.Nat], [Asset], ['query']),
  'getAssetsByCategory' : IDL.Func(
      [AssetCategory],
      [IDL.Vec(Asset)],
      ['query'],
    ),
  'getAssetsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
  'getAssetsByStatus' : IDL.Func([AssetStatus], [IDL.Vec(Asset)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFlexHistory' : IDL.Func([], [IDL.Vec(FlexHistoryEntry)], ['query']),
  'getFlexHistoryForAsset' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FlexHistoryEntry)],
      ['query'],
    ),
  'getHistory' : IDL.Func([], [IDL.Vec(AssignmentHistoryEntry)], ['query']),
  'getHistoryForAsset' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AssignmentHistoryEntry)],
      ['query'],
    ),
  'getMigrationStats' : IDL.Func([], [MigrationStats], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(LocalUser)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'getWarrantyStats' : IDL.Func([], [WarrantyStats], ['query']),
  'hasLocalUsers' : IDL.Func([], [IDL.Bool], ['query']),
  'hasMigratedFromLocalStorage' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdminWithCreds' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginLocalUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Nat,
            'accessLevel' : IDL.Text,
            'name' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'markMigrationComplete' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAssets' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
  'selfRegisterLocalUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateAsset' : IDL.Func([IDL.Nat, AssetInput], [], []),
  'updateAssetWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, AssetInput],
      [],
      [],
    ),
  'updateLocalUser' : IDL.Func([IDL.Nat, LocalUserInput], [], []),
  'updateLocalUserWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, LocalUserInput],
      [],
      [],
    ),
  'updateSoftware' : IDL.Func([IDL.Nat, StoreSoftwareInput], [], []),
  'updateSoftwareWithCreds' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, StoreSoftwareInput],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AssetStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'inStorage' : IDL.Null,
    'available' : IDL.Null,
    'inRepair' : IDL.Null,
    'retired' : IDL.Null,
  });
  const AssetCategory = IDL.Variant({
    'desktop' : IDL.Null,
    'other' : IDL.Null,
    'laptop' : IDL.Null,
    'server' : IDL.Null,
    'printer' : IDL.Null,
    'monitor' : IDL.Null,
    'peripheral' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AssetInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'ram' : IDL.Opt(IDL.Text),
    'status' : AssetStatus,
    'employeeCode' : IDL.Opt(IDL.Text),
    'windowsVersion' : IDL.Opt(IDL.Text),
    'purchaseDate' : IDL.Opt(IDL.Text),
    'storage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'invoiceNumber' : IDL.Opt(IDL.Text),
    'serialNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : AssetCategory,
    'warrantyDate' : IDL.Opt(IDL.Text),
    'assignedUser' : IDL.Opt(IDL.Text),
    'assetTag' : IDL.Opt(IDL.Text),
    'processorType' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'vendorName' : IDL.Opt(IDL.Text),
    'photoId' : IDL.Opt(ExternalBlob),
  });
  const HistoryEntryInput = IDL.Record({
    'action' : IDL.Text,
    'changedBy' : IDL.Text,
    'newAssignee' : IDL.Opt(IDL.Text),
    'assetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'assetName' : IDL.Text,
    'assetType' : IDL.Text,
    'previousAssignee' : IDL.Opt(IDL.Text),
  });
  const LocalUserInput = IDL.Record({
    'accessLevel' : IDL.Text,
    'employeeCode' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'department' : IDL.Text,
  });
  const StoreSoftwareInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'assignedTo' : IDL.Opt(IDL.Text),
    'purchaseDate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'invoiceNumber' : IDL.Opt(IDL.Text),
    'licenseType' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'licenseKey' : IDL.Opt(IDL.Text),
    'assetTag' : IDL.Opt(IDL.Text),
    'licenseExpiry' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Time = IDL.Int;
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'ram' : IDL.Opt(IDL.Text),
    'status' : AssetStatus,
    'employeeCode' : IDL.Opt(IDL.Text),
    'windowsVersion' : IDL.Opt(IDL.Text),
    'purchaseDate' : IDL.Opt(IDL.Text),
    'storage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'invoiceNumber' : IDL.Opt(IDL.Text),
    'serialNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : AssetCategory,
    'warrantyDate' : IDL.Opt(IDL.Text),
    'assignedUser' : IDL.Opt(IDL.Text),
    'assetTag' : IDL.Opt(IDL.Text),
    'processorType' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'vendorName' : IDL.Opt(IDL.Text),
    'photoId' : IDL.Opt(ExternalBlob),
  });
  const LocalUser = IDL.Record({
    'id' : IDL.Nat,
    'accessLevel' : IDL.Text,
    'employeeCode' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'department' : IDL.Text,
  });
  const StoreSoftware = IDL.Record({
    'id' : IDL.Nat,
    'assignedTo' : IDL.Opt(IDL.Text),
    'purchaseDate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'invoiceNumber' : IDL.Opt(IDL.Text),
    'licenseType' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'licenseKey' : IDL.Opt(IDL.Text),
    'assetTag' : IDL.Opt(IDL.Text),
    'licenseExpiry' : IDL.Opt(IDL.Text),
  });
  const UserWithRole = IDL.Record({
    'principal' : Principal,
    'role' : UserRole,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FlexHistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'changedBy' : IDL.Text,
    'newAssignee' : IDL.Opt(IDL.Text),
    'assetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'assetName' : IDL.Text,
    'assetType' : IDL.Text,
    'previousAssignee' : IDL.Opt(IDL.Text),
  });
  const AssignmentHistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'changedBy' : Principal,
    'toStatus' : AssetStatus,
    'assetId' : IDL.Nat,
    'fromStatus' : AssetStatus,
    'toAssignee' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'assetName' : IDL.Text,
    'fromAssignee' : IDL.Opt(IDL.Text),
  });
  const MigrationStats = IDL.Record({
    'historyCount' : IDL.Nat,
    'softwareCount' : IDL.Nat,
    'userCount' : IDL.Nat,
    'assetCount' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'assigned' : IDL.Nat,
    'total' : IDL.Nat,
    'available' : IDL.Nat,
    'inRepair' : IDL.Nat,
  });
  const WarrantyStats = IDL.Record({
    'expiringSoon' : IDL.Nat,
    'total' : IDL.Nat,
    'active' : IDL.Nat,
    'expired' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func([AssetInput], [IDL.Nat], []),
    'addAssetWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, AssetInput],
        [IDL.Nat],
        [],
      ),
    'addHistoryEntry' : IDL.Func([HistoryEntryInput], [IDL.Nat], []),
    'addHistoryEntryWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, HistoryEntryInput],
        [IDL.Nat],
        [],
      ),
    'addLocalUser' : IDL.Func([LocalUserInput], [IDL.Nat], []),
    'addLocalUserWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, LocalUserInput],
        [IDL.Nat],
        [],
      ),
    'addSoftware' : IDL.Func([StoreSoftwareInput], [IDL.Nat], []),
    'addSoftwareWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, StoreSoftwareInput],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([Principal, UserRole], [], []),
    'batchAddAssets' : IDL.Func([IDL.Vec(AssetInput)], [IDL.Vec(IDL.Nat)], []),
    'batchAddHistory' : IDL.Func(
        [IDL.Vec(HistoryEntryInput)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'batchAddSoftware' : IDL.Func(
        [IDL.Vec(StoreSoftwareInput)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'batchAddUsers' : IDL.Func(
        [IDL.Vec(LocalUserInput)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'bootstrapAdmin' : IDL.Func([], [IDL.Bool], []),
    'createFirstLocalUser' : IDL.Func(
        [LocalUserInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'deleteAsset' : IDL.Func([IDL.Nat], [], []),
    'deleteAssetWithCreds' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteLocalUser' : IDL.Func([IDL.Nat], [], []),
    'deleteLocalUserWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'deleteSoftware' : IDL.Func([IDL.Nat], [], []),
    'deleteSoftwareWithCreds' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getAllLocalUsers' : IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
    'getAllSoftware' : IDL.Func([], [IDL.Vec(StoreSoftware)], ['query']),
    'getAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'getAsset' : IDL.Func([IDL.Nat], [Asset], ['query']),
    'getAssetsByCategory' : IDL.Func(
        [AssetCategory],
        [IDL.Vec(Asset)],
        ['query'],
      ),
    'getAssetsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
    'getAssetsByStatus' : IDL.Func([AssetStatus], [IDL.Vec(Asset)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFlexHistory' : IDL.Func([], [IDL.Vec(FlexHistoryEntry)], ['query']),
    'getFlexHistoryForAsset' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FlexHistoryEntry)],
        ['query'],
      ),
    'getHistory' : IDL.Func([], [IDL.Vec(AssignmentHistoryEntry)], ['query']),
    'getHistoryForAsset' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AssignmentHistoryEntry)],
        ['query'],
      ),
    'getMigrationStats' : IDL.Func([], [MigrationStats], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(LocalUser)], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'getWarrantyStats' : IDL.Func([], [WarrantyStats], ['query']),
    'hasLocalUsers' : IDL.Func([], [IDL.Bool], ['query']),
    'hasMigratedFromLocalStorage' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdminWithCreds' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginLocalUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Nat,
              'accessLevel' : IDL.Text,
              'name' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'markMigrationComplete' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAssets' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
    'selfRegisterLocalUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateAsset' : IDL.Func([IDL.Nat, AssetInput], [], []),
    'updateAssetWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, AssetInput],
        [],
        [],
      ),
    'updateLocalUser' : IDL.Func([IDL.Nat, LocalUserInput], [], []),
    'updateLocalUserWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, LocalUserInput],
        [],
        [],
      ),
    'updateSoftware' : IDL.Func([IDL.Nat, StoreSoftwareInput], [], []),
    'updateSoftwareWithCreds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, StoreSoftwareInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };