/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WarrantyStats {
    expiringSoon: bigint;
    total: bigint;
    active: bigint;
    expired: bigint;
}
export interface DataMigrationInput {
    assets: Array<AssetInput>;
    history: Array<HistoryEntryInput>;
    software: Array<StoreSoftwareInput>;
    users: Array<LocalUserInput>;
}
export type Time = bigint;
export interface UserWithRole {
    principal: Principal;
    role: UserRole;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MigrationStats {
    historyCount: bigint;
    softwareCount: bigint;
    userCount: bigint;
    assetCount: bigint;
}
export interface Stats {
    assigned: bigint;
    total: bigint;
    available: bigint;
    inRepair: bigint;
}
export type Principal = Principal;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface HistoryEntryInput {
    action: string;
    changedBy: string;
    newAssignee?: string;
    assetId: bigint;
    notes?: string;
    timestamp: bigint;
    assetName: string;
    assetType: string;
    previousAssignee?: string;
}
export interface AssignmentHistoryEntry {
    id: bigint;
    changedBy: Principal;
    toStatus: AssetStatus;
    assetId: bigint;
    fromStatus: AssetStatus;
    toAssignee?: string;
    timestamp: Time;
    assetName: string;
    fromAssignee?: string;
}
export interface StoreSoftwareInput {
    id?: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
}
export interface LocalUser {
    id: bigint;
    accessLevel: string;
    employeeCode: string;
    username: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
}
export interface LocalUserInput {
    accessLevel: string;
    employeeCode: string;
    username: string;
    password: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
}
export interface FlexHistoryEntry {
    id: bigint;
    action: string;
    changedBy: string;
    newAssignee?: string;
    assetId: bigint;
    notes?: string;
    timestamp: bigint;
    assetName: string;
    assetType: string;
    previousAssignee?: string;
}
export interface AssetInput {
    id?: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    windowsVersion?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}
export interface Asset {
    id: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    windowsVersion?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}
export interface StoreSoftware {
    id: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
}
export interface AssetStats {
    assigned: bigint;
    total: bigint;
    inStorage: bigint;
    available: bigint;
    inRepair: bigint;
    retired: bigint;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AssetCategory {
    desktop = "desktop",
    other = "other",
    laptop = "laptop",
    server = "server",
    printer = "printer",
    monitor = "monitor",
    peripheral = "peripheral"
}
export enum AssetStatus {
    assigned = "assigned",
    inStorage = "inStorage",
    available = "available",
    inRepair = "inRepair",
    retired = "retired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptDataMigration(input: DataMigrationInput): Promise<MigrationStats>;
    addAsset(input: AssetInput): Promise<bigint>;
    addAssetWithCreds(adminUsername: string, adminPassword: string, input: AssetInput): Promise<bigint>;
    addFlexHistoryEntry(entry: HistoryEntryInput): Promise<bigint>;
    addHistoryEntry(entry: HistoryEntryInput): Promise<bigint>;
    addHistoryEntryWithCreds(adminUsername: string, adminPassword: string, entry: HistoryEntryInput): Promise<bigint>;
    addLocalUser(input: LocalUserInput): Promise<bigint>;
    addLocalUserWithCreds(adminUsername: string, adminPassword: string, input: LocalUserInput): Promise<bigint>;
    addSoftware(input: StoreSoftwareInput): Promise<bigint>;
    addSoftwareWithCreds(adminUsername: string, adminPassword: string, input: StoreSoftwareInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    batchAddAssets(inputs: Array<AssetInput>): Promise<Array<bigint>>;
    batchAddHistory(entries: Array<HistoryEntryInput>): Promise<Array<bigint>>;
    batchAddSoftware(inputs: Array<StoreSoftwareInput>): Promise<Array<bigint>>;
    batchAddUsers(inputs: Array<LocalUserInput>): Promise<Array<bigint>>;
    bootstrapAdmin(): Promise<boolean>;
    createFirstLocalUser(input: LocalUserInput): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteAsset(id: bigint): Promise<void>;
    deleteAssetWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void>;
    deleteLocalUser(id: bigint): Promise<void>;
    deleteLocalUserWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void>;
    deleteSoftware(id: bigint): Promise<void>;
    deleteSoftwareWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void>;
    getAllAssets(): Promise<Array<Asset>>;
    getAllAssetsWithCreds(username: string, password: string): Promise<Array<Asset>>;
    getAllFlexHistory(): Promise<Array<FlexHistoryEntry>>;
    getAllLocalUsers(): Promise<Array<LocalUser>>;
    getAllLocalUsersWithCreds(adminUsername: string, adminPassword: string): Promise<Array<LocalUser>>;
    getAllSoftware(): Promise<Array<StoreSoftware>>;
    getAllSoftwareWithCreds(username: string, password: string): Promise<Array<StoreSoftware>>;
    getAllUsersWithRoles(): Promise<Array<UserWithRole>>;
    getAsset(id: bigint): Promise<Asset>;
    getAssetStats(adminUsername: string, adminPassword: string): Promise<AssetStats>;
    getAssetsByCategory(category: AssetCategory): Promise<Array<Asset>>;
    getAssetsByLocation(location: string): Promise<Array<Asset>>;
    getAssetsByStatus(status: AssetStatus): Promise<Array<Asset>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFlexHistory(): Promise<Array<FlexHistoryEntry>>;
    getFlexHistoryByAsset(assetId: bigint): Promise<Array<FlexHistoryEntry>>;
    getFlexHistoryForAsset(assetId: bigint): Promise<Array<FlexHistoryEntry>>;
    getFlexHistoryWithCreds(username: string, password: string): Promise<Array<FlexHistoryEntry>>;
    getHistory(): Promise<Array<AssignmentHistoryEntry>>;
    getHistoryForAsset(assetId: bigint): Promise<Array<AssignmentHistoryEntry>>;
    getMigrationStats(): Promise<MigrationStats>;
    getStats(): Promise<Stats>;
    getUserByUsername(username: string): Promise<LocalUser | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWarrantyStats(): Promise<WarrantyStats>;
    hasLocalUsers(): Promise<boolean>;
    hasMigratedFromLocalStorage(): Promise<boolean>;
    isAdminWithCreds(adminUsername: string, adminPassword: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    loginLocalUser(username: string, password: string): Promise<{
        id: bigint;
        accessLevel: string;
        name: string;
    } | null>;
    markMigrationComplete(): Promise<void>;
    migrateHistoryFromFrontend(entries: Array<HistoryEntryInput>): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAssets(term: string): Promise<Array<Asset>>;
    selfRegisterLocalUser(username: string, password: string, name: string, accessLevel: string): Promise<boolean>;
    updateAsset(id: bigint, input: AssetInput): Promise<void>;
    updateAssetWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: AssetInput): Promise<void>;
    updateLocalUser(id: bigint, input: LocalUserInput): Promise<void>;
    updateLocalUserWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: LocalUserInput): Promise<void>;
    updateSoftware(id: bigint, input: StoreSoftwareInput): Promise<void>;
    updateSoftwareWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: StoreSoftwareInput): Promise<void>;
}
import type { Asset as _Asset, AssetCategory as _AssetCategory, AssetInput as _AssetInput, AssetStatus as _AssetStatus, AssignmentHistoryEntry as _AssignmentHistoryEntry, DataMigrationInput as _DataMigrationInput, ExternalBlob as _ExternalBlob, FlexHistoryEntry as _FlexHistoryEntry, HistoryEntryInput as _HistoryEntryInput, LocalUser as _LocalUser, LocalUserInput as _LocalUserInput, Principal as _Principal, StoreSoftware as _StoreSoftware, StoreSoftwareInput as _StoreSoftwareInput, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserWithRole as _UserWithRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptDataMigration(arg0: DataMigrationInput): Promise<MigrationStats> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDataMigration(await to_candid_DataMigrationInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDataMigration(await to_candid_DataMigrationInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addAsset(arg0: AssetInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addAssetWithCreds(arg0: string, arg1: string, arg2: AssetInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAssetWithCreds(arg0, arg1, await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAssetWithCreds(arg0, arg1, await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addFlexHistoryEntry(arg0: HistoryEntryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlexHistoryEntry(to_candid_HistoryEntryInput_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlexHistoryEntry(to_candid_HistoryEntryInput_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addHistoryEntry(arg0: HistoryEntryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHistoryEntry(to_candid_HistoryEntryInput_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHistoryEntry(to_candid_HistoryEntryInput_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addHistoryEntryWithCreds(arg0: string, arg1: string, arg2: HistoryEntryInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHistoryEntryWithCreds(arg0, arg1, to_candid_HistoryEntryInput_n19(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHistoryEntryWithCreds(arg0, arg1, to_candid_HistoryEntryInput_n19(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addLocalUser(arg0: LocalUserInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocalUser(to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocalUser(to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLocalUserWithCreds(arg0: string, arg1: string, arg2: LocalUserInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocalUserWithCreds(arg0, arg1, to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocalUserWithCreds(arg0, arg1, to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addSoftware(arg0: StoreSoftwareInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoftware(to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoftware(to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSoftwareWithCreds(arg0: string, arg1: string, arg2: StoreSoftwareInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoftwareWithCreds(arg0, arg1, to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoftwareWithCreds(arg0, arg1, to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchAddAssets(arg0: Array<AssetInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.batchAddAssets(await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchAddAssets(await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchAddHistory(arg0: Array<HistoryEntryInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.batchAddHistory(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchAddHistory(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchAddSoftware(arg0: Array<StoreSoftwareInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.batchAddSoftware(to_candid_vec_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchAddSoftware(to_candid_vec_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchAddUsers(arg0: Array<LocalUserInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.batchAddUsers(to_candid_vec_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchAddUsers(to_candid_vec_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bootstrapAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdmin();
            return result;
        }
    }
    async createFirstLocalUser(arg0: LocalUserInput): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createFirstLocalUser(to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFirstLocalUser(to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteAssetWithCreds(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssetWithCreds(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssetWithCreds(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteLocalUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocalUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocalUser(arg0);
            return result;
        }
    }
    async deleteLocalUserWithCreds(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocalUserWithCreds(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocalUserWithCreds(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteSoftware(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSoftware(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSoftware(arg0);
            return result;
        }
    }
    async deleteSoftwareWithCreds(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSoftwareWithCreds(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSoftwareWithCreds(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAssetsWithCreds(arg0: string, arg1: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssetsWithCreds(arg0, arg1);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssetsWithCreds(arg0, arg1);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFlexHistory(): Promise<Array<FlexHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFlexHistory();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFlexHistory();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLocalUsers(): Promise<Array<LocalUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocalUsers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocalUsers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLocalUsersWithCreds(arg0: string, arg1: string): Promise<Array<LocalUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocalUsersWithCreds(arg0, arg1);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocalUsersWithCreds(arg0, arg1);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSoftware(): Promise<Array<StoreSoftware>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSoftware();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSoftware();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSoftwareWithCreds(arg0: string, arg1: string): Promise<Array<StoreSoftware>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSoftwareWithCreds(arg0, arg1);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSoftwareWithCreds(arg0, arg1);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersWithRoles(): Promise<Array<UserWithRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithRoles();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithRoles();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAsset(arg0: bigint): Promise<Asset> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_Asset_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_Asset_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetStats(arg0: string, arg1: string): Promise<AssetStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetStats(arg0, arg1);
            return result;
        }
    }
    async getAssetsByCategory(arg0: AssetCategory): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByCategory(to_candid_AssetCategory_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByCategory(to_candid_AssetCategory_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByLocation(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByLocation(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByLocation(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByStatus(arg0: AssetStatus): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByStatus(to_candid_AssetStatus_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByStatus(to_candid_AssetStatus_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlexHistory(): Promise<Array<FlexHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlexHistory();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlexHistory();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlexHistoryByAsset(arg0: bigint): Promise<Array<FlexHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlexHistoryByAsset(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlexHistoryByAsset(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlexHistoryForAsset(arg0: bigint): Promise<Array<FlexHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlexHistoryForAsset(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlexHistoryForAsset(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlexHistoryWithCreds(arg0: string, arg1: string): Promise<Array<FlexHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlexHistoryWithCreds(arg0, arg1);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlexHistoryWithCreds(arg0, arg1);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistory(): Promise<Array<AssignmentHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoryForAsset(arg0: bigint): Promise<Array<AssignmentHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryForAsset(arg0);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryForAsset(arg0);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMigrationStats(): Promise<MigrationStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMigrationStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMigrationStats();
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserByUsername(arg0: string): Promise<LocalUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWarrantyStats(): Promise<WarrantyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarrantyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarrantyStats();
            return result;
        }
    }
    async hasLocalUsers(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLocalUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLocalUsers();
            return result;
        }
    }
    async hasMigratedFromLocalStorage(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasMigratedFromLocalStorage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasMigratedFromLocalStorage();
            return result;
        }
    }
    async isAdminWithCreds(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminWithCreds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminWithCreds(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginLocalUser(arg0: string, arg1: string): Promise<{
        id: bigint;
        accessLevel: string;
        name: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginLocalUser(arg0, arg1);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginLocalUser(arg0, arg1);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMigrationComplete(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMigrationComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMigrationComplete();
            return result;
        }
    }
    async migrateHistoryFromFrontend(arg0: Array<HistoryEntryInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.migrateHistoryFromFrontend(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrateHistoryFromFrontend(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAssets(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAssets(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAssets(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async selfRegisterLocalUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.selfRegisterLocalUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfRegisterLocalUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAsset(arg0: bigint, arg1: AssetInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateAssetWithCreds(arg0: string, arg1: string, arg2: bigint, arg3: AssetInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetWithCreds(arg0, arg1, arg2, await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetWithCreds(arg0, arg1, arg2, await to_candid_AssetInput_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateLocalUser(arg0: bigint, arg1: LocalUserInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalUser(arg0, to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalUser(arg0, to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLocalUserWithCreds(arg0: string, arg1: string, arg2: bigint, arg3: LocalUserInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalUserWithCreds(arg0, arg1, arg2, to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalUserWithCreds(arg0, arg1, arg2, to_candid_LocalUserInput_n25(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateSoftware(arg0: bigint, arg1: StoreSoftwareInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSoftware(arg0, to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSoftware(arg0, to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSoftwareWithCreds(arg0: string, arg1: string, arg2: bigint, arg3: StoreSoftwareInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSoftwareWithCreds(arg0, arg1, arg2, to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSoftwareWithCreds(arg0, arg1, arg2, to_candid_StoreSoftwareInput_n22(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_AssetCategory_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetCategory): AssetCategory {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_AssetStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetStatus): AssetStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Asset_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Promise<Asset> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_AssignmentHistoryEntry_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentHistoryEntry): AssignmentHistoryEntry {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FlexHistoryEntry_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlexHistoryEntry): FlexHistoryEntry {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_LocalUser_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocalUser): LocalUser {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_StoreSoftware_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreSoftware): StoreSoftware {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserWithRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserWithRole): UserWithRole {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocalUser]): LocalUser | null {
    return value.length === 0 ? null : from_candid_LocalUser_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: bigint;
        accessLevel: string;
        name: string;
    }]): {
    id: bigint;
    accessLevel: string;
    name: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ram: [] | [string];
    status: _AssetStatus;
    employeeCode: [] | [string];
    windowsVersion: [] | [string];
    purchaseDate: [] | [string];
    storage: [] | [string];
    name: string;
    createdAt: _Time;
    invoiceNumber: [] | [string];
    serialNumber: string;
    notes: [] | [string];
    category: _AssetCategory;
    warrantyDate: [] | [string];
    assignedUser: [] | [string];
    assetTag: [] | [string];
    processorType: [] | [string];
    location: string;
    vendorName: [] | [string];
    photoId: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    windowsVersion?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}> {
    return {
        id: value.id,
        ram: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.ram)),
        status: from_candid_AssetStatus_n34(_uploadFile, _downloadFile, value.status),
        employeeCode: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.employeeCode)),
        windowsVersion: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.windowsVersion)),
        purchaseDate: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.purchaseDate)),
        storage: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.storage)),
        name: value.name,
        createdAt: value.createdAt,
        invoiceNumber: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.invoiceNumber)),
        serialNumber: value.serialNumber,
        notes: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_AssetCategory_n36(_uploadFile, _downloadFile, value.category),
        warrantyDate: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.warrantyDate)),
        assignedUser: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.assignedUser)),
        assetTag: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.assetTag)),
        processorType: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.processorType)),
        location: value.location,
        vendorName: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.vendorName)),
        photoId: record_opt_to_undefined(await from_candid_opt_n38(_uploadFile, _downloadFile, value.photoId))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    changedBy: string;
    newAssignee: [] | [string];
    assetId: bigint;
    notes: [] | [string];
    timestamp: bigint;
    assetName: string;
    assetType: string;
    previousAssignee: [] | [string];
}): {
    id: bigint;
    action: string;
    changedBy: string;
    newAssignee?: string;
    assetId: bigint;
    notes?: string;
    timestamp: bigint;
    assetName: string;
    assetType: string;
    previousAssignee?: string;
} {
    return {
        id: value.id,
        action: value.action,
        changedBy: value.changedBy,
        newAssignee: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.newAssignee)),
        assetId: value.assetId,
        notes: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        assetName: value.assetName,
        assetType: value.assetType,
        previousAssignee: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.previousAssignee))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    accessLevel: string;
    employeeCode: string;
    username: string;
    name: string;
    email: string;
    notes: [] | [string];
    department: string;
}): {
    id: bigint;
    accessLevel: string;
    employeeCode: string;
    username: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
} {
    return {
        id: value.id,
        accessLevel: value.accessLevel,
        employeeCode: value.employeeCode,
        username: value.username,
        name: value.name,
        email: value.email,
        notes: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.notes)),
        department: value.department
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignedTo: [] | [string];
    purchaseDate: [] | [string];
    name: string;
    createdAt: _Time;
    invoiceNumber: [] | [string];
    licenseType: [] | [string];
    vendor: string;
    notes: [] | [string];
    licenseKey: [] | [string];
    assetTag: [] | [string];
    licenseExpiry: [] | [string];
}): {
    id: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
} {
    return {
        id: value.id,
        assignedTo: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.assignedTo)),
        purchaseDate: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.purchaseDate)),
        name: value.name,
        createdAt: value.createdAt,
        invoiceNumber: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.invoiceNumber)),
        licenseType: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.licenseType)),
        vendor: value.vendor,
        notes: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.notes)),
        licenseKey: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.licenseKey)),
        assetTag: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.assetTag)),
        licenseExpiry: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.licenseExpiry))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n52(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    changedBy: _Principal;
    toStatus: _AssetStatus;
    assetId: bigint;
    fromStatus: _AssetStatus;
    toAssignee: [] | [string];
    timestamp: _Time;
    assetName: string;
    fromAssignee: [] | [string];
}): {
    id: bigint;
    changedBy: Principal;
    toStatus: AssetStatus;
    assetId: bigint;
    fromStatus: AssetStatus;
    toAssignee?: string;
    timestamp: Time;
    assetName: string;
    fromAssignee?: string;
} {
    return {
        id: value.id,
        changedBy: value.changedBy,
        toStatus: from_candid_AssetStatus_n34(_uploadFile, _downloadFile, value.toStatus),
        assetId: value.assetId,
        fromStatus: from_candid_AssetStatus_n34(_uploadFile, _downloadFile, value.fromStatus),
        toAssignee: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.toAssignee)),
        timestamp: value.timestamp,
        assetName: value.assetName,
        fromAssignee: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.fromAssignee))
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    inStorage: null;
} | {
    available: null;
} | {
    inRepair: null;
} | {
    retired: null;
}): AssetStatus {
    return "assigned" in value ? AssetStatus.assigned : "inStorage" in value ? AssetStatus.inStorage : "available" in value ? AssetStatus.available : "inRepair" in value ? AssetStatus.inRepair : "retired" in value ? AssetStatus.retired : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desktop: null;
} | {
    other: null;
} | {
    laptop: null;
} | {
    server: null;
} | {
    printer: null;
} | {
    monitor: null;
} | {
    peripheral: null;
}): AssetCategory {
    return "desktop" in value ? AssetCategory.desktop : "other" in value ? AssetCategory.other : "laptop" in value ? AssetCategory.laptop : "server" in value ? AssetCategory.server : "printer" in value ? AssetCategory.printer : "monitor" in value ? AssetCategory.monitor : "peripheral" in value ? AssetCategory.peripheral : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Promise<Array<Asset>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Asset_n31(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlexHistoryEntry>): Array<FlexHistoryEntry> {
    return value.map((x)=>from_candid_FlexHistoryEntry_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocalUser>): Array<LocalUser> {
    return value.map((x)=>from_candid_LocalUser_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoreSoftware>): Array<StoreSoftware> {
    return value.map((x)=>from_candid_StoreSoftware_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserWithRole>): Array<UserWithRole> {
    return value.map((x)=>from_candid_UserWithRole_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssignmentHistoryEntry>): Array<AssignmentHistoryEntry> {
    return value.map((x)=>from_candid_AssignmentHistoryEntry_n56(_uploadFile, _downloadFile, x));
}
function to_candid_AssetCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategory): _AssetCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_AssetInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetInput): Promise<_AssetInput> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_AssetStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStatus): _AssetStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_DataMigrationInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DataMigrationInput): Promise<_DataMigrationInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HistoryEntryInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HistoryEntryInput): _HistoryEntryInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_LocalUserInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocalUserInput): _LocalUserInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_StoreSoftwareInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreSoftwareInput): _StoreSoftwareInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    windowsVersion?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}): Promise<{
    id: [] | [bigint];
    ram: [] | [string];
    status: _AssetStatus;
    employeeCode: [] | [string];
    windowsVersion: [] | [string];
    purchaseDate: [] | [string];
    storage: [] | [string];
    name: string;
    invoiceNumber: [] | [string];
    serialNumber: string;
    notes: [] | [string];
    category: _AssetCategory;
    warrantyDate: [] | [string];
    assignedUser: [] | [string];
    assetTag: [] | [string];
    processorType: [] | [string];
    location: string;
    vendorName: [] | [string];
    photoId: [] | [_ExternalBlob];
}> {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        ram: value.ram ? candid_some(value.ram) : candid_none(),
        status: to_candid_AssetStatus_n13(_uploadFile, _downloadFile, value.status),
        employeeCode: value.employeeCode ? candid_some(value.employeeCode) : candid_none(),
        windowsVersion: value.windowsVersion ? candid_some(value.windowsVersion) : candid_none(),
        purchaseDate: value.purchaseDate ? candid_some(value.purchaseDate) : candid_none(),
        storage: value.storage ? candid_some(value.storage) : candid_none(),
        name: value.name,
        invoiceNumber: value.invoiceNumber ? candid_some(value.invoiceNumber) : candid_none(),
        serialNumber: value.serialNumber,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: to_candid_AssetCategory_n15(_uploadFile, _downloadFile, value.category),
        warrantyDate: value.warrantyDate ? candid_some(value.warrantyDate) : candid_none(),
        assignedUser: value.assignedUser ? candid_some(value.assignedUser) : candid_none(),
        assetTag: value.assetTag ? candid_some(value.assetTag) : candid_none(),
        processorType: value.processorType ? candid_some(value.processorType) : candid_none(),
        location: value.location,
        vendorName: value.vendorName ? candid_some(value.vendorName) : candid_none(),
        photoId: value.photoId ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.photoId)) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: string;
    changedBy: string;
    newAssignee?: string;
    assetId: bigint;
    notes?: string;
    timestamp: bigint;
    assetName: string;
    assetType: string;
    previousAssignee?: string;
}): {
    action: string;
    changedBy: string;
    newAssignee: [] | [string];
    assetId: bigint;
    notes: [] | [string];
    timestamp: bigint;
    assetName: string;
    assetType: string;
    previousAssignee: [] | [string];
} {
    return {
        action: value.action,
        changedBy: value.changedBy,
        newAssignee: value.newAssignee ? candid_some(value.newAssignee) : candid_none(),
        assetId: value.assetId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        timestamp: value.timestamp,
        assetName: value.assetName,
        assetType: value.assetType,
        previousAssignee: value.previousAssignee ? candid_some(value.previousAssignee) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
}): {
    id: [] | [bigint];
    assignedTo: [] | [string];
    purchaseDate: [] | [string];
    name: string;
    invoiceNumber: [] | [string];
    licenseType: [] | [string];
    vendor: string;
    notes: [] | [string];
    licenseKey: [] | [string];
    assetTag: [] | [string];
    licenseExpiry: [] | [string];
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        assignedTo: value.assignedTo ? candid_some(value.assignedTo) : candid_none(),
        purchaseDate: value.purchaseDate ? candid_some(value.purchaseDate) : candid_none(),
        name: value.name,
        invoiceNumber: value.invoiceNumber ? candid_some(value.invoiceNumber) : candid_none(),
        licenseType: value.licenseType ? candid_some(value.licenseType) : candid_none(),
        vendor: value.vendor,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        licenseKey: value.licenseKey ? candid_some(value.licenseKey) : candid_none(),
        assetTag: value.assetTag ? candid_some(value.assetTag) : candid_none(),
        licenseExpiry: value.licenseExpiry ? candid_some(value.licenseExpiry) : candid_none()
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessLevel: string;
    employeeCode: string;
    username: string;
    password: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
}): {
    accessLevel: string;
    employeeCode: string;
    username: string;
    password: string;
    name: string;
    email: string;
    notes: [] | [string];
    department: string;
} {
    return {
        accessLevel: value.accessLevel,
        employeeCode: value.employeeCode,
        username: value.username,
        password: value.password,
        name: value.name,
        email: value.email,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        department: value.department
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assets: Array<AssetInput>;
    history: Array<HistoryEntryInput>;
    software: Array<StoreSoftwareInput>;
    users: Array<LocalUserInput>;
}): Promise<{
    assets: Array<_AssetInput>;
    history: Array<_HistoryEntryInput>;
    software: Array<_StoreSoftwareInput>;
    users: Array<_LocalUserInput>;
}> {
    return {
        assets: await to_candid_vec_n10(_uploadFile, _downloadFile, value.assets),
        history: to_candid_vec_n18(_uploadFile, _downloadFile, value.history),
        software: to_candid_vec_n21(_uploadFile, _downloadFile, value.software),
        users: to_candid_vec_n24(_uploadFile, _downloadFile, value.users)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStatus): {
    assigned: null;
} | {
    inStorage: null;
} | {
    available: null;
} | {
    inRepair: null;
} | {
    retired: null;
} {
    return value == AssetStatus.assigned ? {
        assigned: null
    } : value == AssetStatus.inStorage ? {
        inStorage: null
    } : value == AssetStatus.available ? {
        available: null
    } : value == AssetStatus.inRepair ? {
        inRepair: null
    } : value == AssetStatus.retired ? {
        retired: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategory): {
    desktop: null;
} | {
    other: null;
} | {
    laptop: null;
} | {
    server: null;
} | {
    printer: null;
} | {
    monitor: null;
} | {
    peripheral: null;
} {
    return value == AssetCategory.desktop ? {
        desktop: null
    } : value == AssetCategory.other ? {
        other: null
    } : value == AssetCategory.laptop ? {
        laptop: null
    } : value == AssetCategory.server ? {
        server: null
    } : value == AssetCategory.printer ? {
        printer: null
    } : value == AssetCategory.monitor ? {
        monitor: null
    } : value == AssetCategory.peripheral ? {
        peripheral: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AssetInput>): Promise<Array<_AssetInput>> {
    return await Promise.all(value.map(async (x)=>await to_candid_AssetInput_n11(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HistoryEntryInput>): Array<_HistoryEntryInput> {
    return value.map((x)=>to_candid_HistoryEntryInput_n19(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StoreSoftwareInput>): Array<_StoreSoftwareInput> {
    return value.map((x)=>to_candid_StoreSoftwareInput_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LocalUserInput>): Array<_LocalUserInput> {
    return value.map((x)=>to_candid_LocalUserInput_n25(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
