/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WarrantyStats {
    expiringSoon: bigint;
    total: bigint;
    active: bigint;
    expired: bigint;
}
export type Time = bigint;
export interface UserWithRole {
    principal: Principal;
    role: UserRole;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Stats {
    assigned: bigint;
    total: bigint;
    available: bigint;
    inRepair: bigint;
}
export type Principal = Principal;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AssignmentHistoryEntry {
    id: bigint;
    changedBy: Principal;
    toStatus: AssetStatus;
    assetId: bigint;
    fromStatus: AssetStatus;
    toAssignee?: string;
    timestamp: Time;
    assetName: string;
    fromAssignee?: string;
}
export interface StoreSoftwareInput {
    id?: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
}
export interface LocalUser {
    id: bigint;
    accessLevel: string;
    employeeCode: string;
    username: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
}
export interface LocalUserInput {
    accessLevel: string;
    employeeCode: string;
    username: string;
    password: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
}
export interface AssetInput {
    id?: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}
export interface Asset {
    id: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}
export interface StoreSoftware {
    id: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AssetCategory {
    desktop = "desktop",
    other = "other",
    laptop = "laptop",
    server = "server",
    printer = "printer",
    monitor = "monitor",
    peripheral = "peripheral"
}
export enum AssetStatus {
    assigned = "assigned",
    inStorage = "inStorage",
    available = "available",
    inRepair = "inRepair",
    retired = "retired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAsset(input: AssetInput): Promise<bigint>;
    addLocalUser(input: LocalUserInput): Promise<bigint>;
    addSoftware(input: StoreSoftwareInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapAdmin(): Promise<boolean>;
    deleteAsset(id: bigint): Promise<void>;
    deleteLocalUser(id: bigint): Promise<void>;
    deleteSoftware(id: bigint): Promise<void>;
    getAllAssets(): Promise<Array<Asset>>;
    getAllLocalUsers(): Promise<Array<LocalUser>>;
    getAllSoftware(): Promise<Array<StoreSoftware>>;
    getAllUsersWithRoles(): Promise<Array<UserWithRole>>;
    getAsset(id: bigint): Promise<Asset>;
    getAssetsByCategory(category: AssetCategory): Promise<Array<Asset>>;
    getAssetsByLocation(location: string): Promise<Array<Asset>>;
    getAssetsByStatus(status: AssetStatus): Promise<Array<Asset>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHistory(): Promise<Array<AssignmentHistoryEntry>>;
    getHistoryForAsset(assetId: bigint): Promise<Array<AssignmentHistoryEntry>>;
    getStats(): Promise<Stats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWarrantyStats(): Promise<WarrantyStats>;
    isCallerAdmin(): Promise<boolean>;
    loginLocalUser(username: string, password: string): Promise<{
        id: bigint;
        accessLevel: string;
        name: string;
    } | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAssets(term: string): Promise<Array<Asset>>;
    updateAsset(id: bigint, input: AssetInput): Promise<void>;
    updateLocalUser(id: bigint, input: LocalUserInput): Promise<void>;
    updateSoftware(id: bigint, input: StoreSoftwareInput): Promise<void>;
    addAssetWithCreds(adminUsername: string, adminPassword: string, input: AssetInput): Promise<bigint>;
    updateAssetWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: AssetInput): Promise<void>;
    deleteAssetWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void>;
    addSoftwareWithCreds(adminUsername: string, adminPassword: string, input: StoreSoftwareInput): Promise<bigint>;
    updateSoftwareWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: StoreSoftwareInput): Promise<void>;
    deleteSoftwareWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void>;
    addLocalUserWithCreds(adminUsername: string, adminPassword: string, input: LocalUserInput): Promise<bigint>;
    updateLocalUserWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: LocalUserInput): Promise<void>;
    deleteLocalUserWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void>;
    isAdminWithCreds(adminUsername: string, adminPassword: string): Promise<boolean>;
    selfRegisterLocalUser(username: string, password: string, name: string, accessLevel: string): Promise<boolean>;
    createFirstLocalUser(input: LocalUserInput): Promise<{ ok: bigint } | { err: string }>;
    hasLocalUsers(): Promise<boolean>;
}
import type { Asset as _Asset, AssetCategory as _AssetCategory, AssetInput as _AssetInput, AssetStatus as _AssetStatus, AssignmentHistoryEntry as _AssignmentHistoryEntry, ExternalBlob as _ExternalBlob, LocalUser as _LocalUser, LocalUserInput as _LocalUserInput, Principal as _Principal, StoreSoftware as _StoreSoftware, StoreSoftwareInput as _StoreSoftwareInput, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserWithRole as _UserWithRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAsset(arg0: AssetInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLocalUser(arg0: LocalUserInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocalUser(to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocalUser(to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSoftware(arg0: StoreSoftwareInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoftware(to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoftware(to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdmin();
            return result;
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteLocalUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocalUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocalUser(arg0);
            return result;
        }
    }
    async deleteSoftware(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSoftware(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSoftware(arg0);
            return result;
        }
    }
    async getAllAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLocalUsers(): Promise<Array<LocalUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocalUsers();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocalUsers();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSoftware(): Promise<Array<StoreSoftware>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSoftware();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSoftware();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersWithRoles(): Promise<Array<UserWithRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithRoles();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithRoles();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAsset(arg0: bigint): Promise<Asset> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_Asset_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_Asset_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByCategory(arg0: AssetCategory): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByCategory(to_candid_AssetCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByCategory(to_candid_AssetCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByLocation(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByLocation(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByLocation(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByStatus(arg0: AssetStatus): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByStatus(to_candid_AssetStatus_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByStatus(to_candid_AssetStatus_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistory(): Promise<Array<AssignmentHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoryForAsset(arg0: bigint): Promise<Array<AssignmentHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryForAsset(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryForAsset(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWarrantyStats(): Promise<WarrantyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarrantyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarrantyStats();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginLocalUser(arg0: string, arg1: string): Promise<{
        id: bigint;
        accessLevel: string;
        name: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginLocalUser(arg0, arg1);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginLocalUser(arg0, arg1);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAssets(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAssets(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAssets(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAsset(arg0: bigint, arg1: AssetInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLocalUser(arg0: bigint, arg1: LocalUserInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalUser(arg0, to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalUser(arg0, to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSoftware(arg0: bigint, arg1: StoreSoftwareInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSoftware(arg0, to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSoftware(arg0, to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }

    async addAssetWithCreds(adminUsername: string, adminPassword: string, input: AssetInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAssetWithCreds(adminUsername, adminPassword, await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, input));
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.addAssetWithCreds(adminUsername, adminPassword, await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, input));
            return result;
        }
    }
    async updateAssetWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: AssetInput): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateAssetWithCreds(adminUsername, adminPassword, id, await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, input));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            await this.actor.updateAssetWithCreds(adminUsername, adminPassword, id, await to_candid_AssetInput_n8(this._uploadFile, this._downloadFile, input));
        }
    }
    async deleteAssetWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteAssetWithCreds(adminUsername, adminPassword, id);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            await this.actor.deleteAssetWithCreds(adminUsername, adminPassword, id);
        }
    }
    async addSoftwareWithCreds(adminUsername: string, adminPassword: string, input: StoreSoftwareInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoftwareWithCreds(adminUsername, adminPassword, to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, input));
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.addSoftwareWithCreds(adminUsername, adminPassword, to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, input));
            return result;
        }
    }
    async updateSoftwareWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: StoreSoftwareInput): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateSoftwareWithCreds(adminUsername, adminPassword, id, to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, input));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            await this.actor.updateSoftwareWithCreds(adminUsername, adminPassword, id, to_candid_StoreSoftwareInput_n17(this._uploadFile, this._downloadFile, input));
        }
    }
    async deleteSoftwareWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteSoftwareWithCreds(adminUsername, adminPassword, id);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            await this.actor.deleteSoftwareWithCreds(adminUsername, adminPassword, id);
        }
    }
    async addLocalUserWithCreds(adminUsername: string, adminPassword: string, input: LocalUserInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocalUserWithCreds(adminUsername, adminPassword, to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, input));
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.addLocalUserWithCreds(adminUsername, adminPassword, to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, input));
            return result;
        }
    }
    async updateLocalUserWithCreds(adminUsername: string, adminPassword: string, id: bigint, input: LocalUserInput): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateLocalUserWithCreds(adminUsername, adminPassword, id, to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, input));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            await this.actor.updateLocalUserWithCreds(adminUsername, adminPassword, id, to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, input));
        }
    }
    async deleteLocalUserWithCreds(adminUsername: string, adminPassword: string, id: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteLocalUserWithCreds(adminUsername, adminPassword, id);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            await this.actor.deleteLocalUserWithCreds(adminUsername, adminPassword, id);
        }
    }
    async isAdminWithCreds(adminUsername: string, adminPassword: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminWithCreds(adminUsername, adminPassword);
                return result;
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.isAdminWithCreds(adminUsername, adminPassword);
            return result;
        }
    }
    async createFirstLocalUser(input: LocalUserInput): Promise<{ ok: bigint } | { err: string }> {
        const result = await this.actor.createFirstLocalUser(to_candid_LocalUserInput_n15(this._uploadFile, this._downloadFile, input));
        if ('ok' in result) return { ok: result.ok };
        return { err: result.err };
    }
    async hasLocalUsers(): Promise<boolean> {
        return this.actor.hasLocalUsers();
    }
    async selfRegisterLocalUser(username: string, password: string, name: string, accessLevel: string): Promise<boolean> {
        if (!username || !password) return false;
        try {
            // First try the dedicated selfRegisterLocalUser backend function
            const result = await (this.actor as any).selfRegisterLocalUser(username, password, name, accessLevel);
            // Handle both Bool and variant return types
            if (typeof result === 'boolean') return result;
            if (result && ('ok' in result || 'alreadyExists' in result)) return true;
            return !!result;
        } catch {
            // Fallback: use addLocalUserWithCreds with complete input
            try {
                await (this.actor as any).addLocalUserWithCreds(username, password, {
                    name,
                    username,
                    password,
                    accessLevel,
                    employeeCode: '',
                    department: '',
                    email: '',
                    notes: [],
                } as any);
                return true;
            } catch {
                return false;
            }
        }
    }

}
function from_candid_AssetCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetCategory): AssetCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_AssetStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetStatus): AssetStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Asset_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Promise<Asset> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_AssignmentHistoryEntry_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentHistoryEntry): AssignmentHistoryEntry {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LocalUser_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocalUser): LocalUser {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_StoreSoftware_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreSoftware): StoreSoftware {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserWithRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserWithRole): UserWithRole {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: bigint;
        accessLevel: string;
        name: string;
    }]): {
    id: bigint;
    accessLevel: string;
    name: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ram: [] | [string];
    status: _AssetStatus;
    employeeCode: [] | [string];
    purchaseDate: [] | [string];
    storage: [] | [string];
    name: string;
    createdAt: _Time;
    invoiceNumber: [] | [string];
    serialNumber: string;
    notes: [] | [string];
    category: _AssetCategory;
    warrantyDate: [] | [string];
    assignedUser: [] | [string];
    assetTag: [] | [string];
    processorType: [] | [string];
    location: string;
    vendorName: [] | [string];
    photoId: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}> {
    return {
        id: value.id,
        ram: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.ram)),
        status: from_candid_AssetStatus_n25(_uploadFile, _downloadFile, value.status),
        employeeCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.employeeCode)),
        purchaseDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.purchaseDate)),
        storage: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.storage)),
        name: value.name,
        createdAt: value.createdAt,
        invoiceNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.invoiceNumber)),
        serialNumber: value.serialNumber,
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_AssetCategory_n27(_uploadFile, _downloadFile, value.category),
        warrantyDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.warrantyDate)),
        assignedUser: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.assignedUser)),
        assetTag: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.assetTag)),
        processorType: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.processorType)),
        location: value.location,
        vendorName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.vendorName)),
        photoId: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.photoId))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    accessLevel: string;
    employeeCode: string;
    username: string;
    name: string;
    email: string;
    notes: [] | [string];
    department: string;
}): {
    id: bigint;
    accessLevel: string;
    employeeCode: string;
    username: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
} {
    return {
        id: value.id,
        accessLevel: value.accessLevel,
        employeeCode: value.employeeCode,
        username: value.username,
        name: value.name,
        email: value.email,
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        department: value.department
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignedTo: [] | [string];
    purchaseDate: [] | [string];
    name: string;
    createdAt: _Time;
    invoiceNumber: [] | [string];
    licenseType: [] | [string];
    vendor: string;
    notes: [] | [string];
    licenseKey: [] | [string];
    assetTag: [] | [string];
    licenseExpiry: [] | [string];
}): {
    id: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    createdAt: Time;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
} {
    return {
        id: value.id,
        assignedTo: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.assignedTo)),
        purchaseDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.purchaseDate)),
        name: value.name,
        createdAt: value.createdAt,
        invoiceNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.invoiceNumber)),
        licenseType: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.licenseType)),
        vendor: value.vendor,
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        licenseKey: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.licenseKey)),
        assetTag: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.assetTag)),
        licenseExpiry: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.licenseExpiry))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n40(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    changedBy: _Principal;
    toStatus: _AssetStatus;
    assetId: bigint;
    fromStatus: _AssetStatus;
    toAssignee: [] | [string];
    timestamp: _Time;
    assetName: string;
    fromAssignee: [] | [string];
}): {
    id: bigint;
    changedBy: Principal;
    toStatus: AssetStatus;
    assetId: bigint;
    fromStatus: AssetStatus;
    toAssignee?: string;
    timestamp: Time;
    assetName: string;
    fromAssignee?: string;
} {
    return {
        id: value.id,
        changedBy: value.changedBy,
        toStatus: from_candid_AssetStatus_n25(_uploadFile, _downloadFile, value.toStatus),
        assetId: value.assetId,
        fromStatus: from_candid_AssetStatus_n25(_uploadFile, _downloadFile, value.fromStatus),
        toAssignee: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.toAssignee)),
        timestamp: value.timestamp,
        assetName: value.assetName,
        fromAssignee: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.fromAssignee))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    inStorage: null;
} | {
    available: null;
} | {
    inRepair: null;
} | {
    retired: null;
}): AssetStatus {
    return "assigned" in value ? AssetStatus.assigned : "inStorage" in value ? AssetStatus.inStorage : "available" in value ? AssetStatus.available : "inRepair" in value ? AssetStatus.inRepair : "retired" in value ? AssetStatus.retired : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desktop: null;
} | {
    other: null;
} | {
    laptop: null;
} | {
    server: null;
} | {
    printer: null;
} | {
    monitor: null;
} | {
    peripheral: null;
}): AssetCategory {
    return "desktop" in value ? AssetCategory.desktop : "other" in value ? AssetCategory.other : "laptop" in value ? AssetCategory.laptop : "server" in value ? AssetCategory.server : "printer" in value ? AssetCategory.printer : "monitor" in value ? AssetCategory.monitor : "peripheral" in value ? AssetCategory.peripheral : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Promise<Array<Asset>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Asset_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocalUser>): Array<LocalUser> {
    return value.map((x)=>from_candid_LocalUser_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoreSoftware>): Array<StoreSoftware> {
    return value.map((x)=>from_candid_StoreSoftware_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserWithRole>): Array<UserWithRole> {
    return value.map((x)=>from_candid_UserWithRole_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssignmentHistoryEntry>): Array<AssignmentHistoryEntry> {
    return value.map((x)=>from_candid_AssignmentHistoryEntry_n44(_uploadFile, _downloadFile, x));
}
function to_candid_AssetCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategory): _AssetCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_AssetInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetInput): Promise<_AssetInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AssetStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStatus): _AssetStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LocalUserInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocalUserInput): _LocalUserInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_StoreSoftwareInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreSoftwareInput): _StoreSoftwareInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessLevel: string;
    employeeCode: string;
    username: string;
    password: string;
    name: string;
    email: string;
    notes?: string;
    department: string;
}): {
    accessLevel: string;
    employeeCode: string;
    username: string;
    password: string;
    name: string;
    email: string;
    notes: [] | [string];
    department: string;
} {
    return {
        accessLevel: value.accessLevel,
        employeeCode: value.employeeCode,
        username: value.username,
        password: value.password,
        name: value.name,
        email: value.email,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        department: value.department
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    assignedTo?: string;
    purchaseDate?: string;
    name: string;
    invoiceNumber?: string;
    licenseType?: string;
    vendor: string;
    notes?: string;
    licenseKey?: string;
    assetTag?: string;
    licenseExpiry?: string;
}): {
    id: [] | [bigint];
    assignedTo: [] | [string];
    purchaseDate: [] | [string];
    name: string;
    invoiceNumber: [] | [string];
    licenseType: [] | [string];
    vendor: string;
    notes: [] | [string];
    licenseKey: [] | [string];
    assetTag: [] | [string];
    licenseExpiry: [] | [string];
} {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        assignedTo: value.assignedTo ? candid_some(value.assignedTo) : candid_none(),
        purchaseDate: value.purchaseDate ? candid_some(value.purchaseDate) : candid_none(),
        name: value.name,
        invoiceNumber: value.invoiceNumber ? candid_some(value.invoiceNumber) : candid_none(),
        licenseType: value.licenseType ? candid_some(value.licenseType) : candid_none(),
        vendor: value.vendor,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        licenseKey: value.licenseKey ? candid_some(value.licenseKey) : candid_none(),
        assetTag: value.assetTag ? candid_some(value.assetTag) : candid_none(),
        licenseExpiry: value.licenseExpiry ? candid_some(value.licenseExpiry) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id?: bigint;
    ram?: string;
    status: AssetStatus;
    employeeCode?: string;
    purchaseDate?: string;
    storage?: string;
    name: string;
    invoiceNumber?: string;
    serialNumber: string;
    notes?: string;
    category: AssetCategory;
    warrantyDate?: string;
    assignedUser?: string;
    assetTag?: string;
    processorType?: string;
    location: string;
    vendorName?: string;
    photoId?: ExternalBlob;
}): Promise<{
    id: [] | [bigint];
    ram: [] | [string];
    status: _AssetStatus;
    employeeCode: [] | [string];
    purchaseDate: [] | [string];
    storage: [] | [string];
    name: string;
    invoiceNumber: [] | [string];
    serialNumber: string;
    notes: [] | [string];
    category: _AssetCategory;
    warrantyDate: [] | [string];
    assignedUser: [] | [string];
    assetTag: [] | [string];
    processorType: [] | [string];
    location: string;
    vendorName: [] | [string];
    photoId: [] | [_ExternalBlob];
}> {
    return {
        id: value.id ? candid_some(value.id) : candid_none(),
        ram: value.ram ? candid_some(value.ram) : candid_none(),
        status: to_candid_AssetStatus_n10(_uploadFile, _downloadFile, value.status),
        employeeCode: value.employeeCode ? candid_some(value.employeeCode) : candid_none(),
        purchaseDate: value.purchaseDate ? candid_some(value.purchaseDate) : candid_none(),
        storage: value.storage ? candid_some(value.storage) : candid_none(),
        name: value.name,
        invoiceNumber: value.invoiceNumber ? candid_some(value.invoiceNumber) : candid_none(),
        serialNumber: value.serialNumber,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: to_candid_AssetCategory_n12(_uploadFile, _downloadFile, value.category),
        warrantyDate: value.warrantyDate ? candid_some(value.warrantyDate) : candid_none(),
        assignedUser: value.assignedUser ? candid_some(value.assignedUser) : candid_none(),
        assetTag: value.assetTag ? candid_some(value.assetTag) : candid_none(),
        processorType: value.processorType ? candid_some(value.processorType) : candid_none(),
        location: value.location,
        vendorName: value.vendorName ? candid_some(value.vendorName) : candid_none(),
        photoId: value.photoId ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photoId)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetStatus): {
    assigned: null;
} | {
    inStorage: null;
} | {
    available: null;
} | {
    inRepair: null;
} | {
    retired: null;
} {
    return value == AssetStatus.assigned ? {
        assigned: null
    } : value == AssetStatus.inStorage ? {
        inStorage: null
    } : value == AssetStatus.available ? {
        available: null
    } : value == AssetStatus.inRepair ? {
        inRepair: null
    } : value == AssetStatus.retired ? {
        retired: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetCategory): {
    desktop: null;
} | {
    other: null;
} | {
    laptop: null;
} | {
    server: null;
} | {
    printer: null;
} | {
    monitor: null;
} | {
    peripheral: null;
} {
    return value == AssetCategory.desktop ? {
        desktop: null
    } : value == AssetCategory.other ? {
        other: null
    } : value == AssetCategory.laptop ? {
        laptop: null
    } : value == AssetCategory.server ? {
        server: null
    } : value == AssetCategory.printer ? {
        printer: null
    } : value == AssetCategory.monitor ? {
        monitor: null
    } : value == AssetCategory.peripheral ? {
        peripheral: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
